# --------------------------------------------------------------------------
# 
#               * RealmProtection, by TFAGaming (GitHub) *
#
#     Please read the license before you do any changes to this plugin!
#   
# --------------------------------------------------------------------------

# Links for important info:
# - Material/item names: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html

# The database for the claims, based on SQLite
database:
  path: "/database.db"

# Main config
lands:
  plugins:
    worldguard_regions: true # If enabled, this will block any player to claim a chunk that is protected by WorldGuard
    vaultapi_economy: true # If enabled, this will make any player to use /land deposit and /land withdraw in their land
  ratelimits:
    # Player's land limits for chunks
    chunks:
      default: 10
      vip: 20
      admin: 50
      owner: 100
    # Player's land limits for roles
    roles:
      default: 5
      vip: 10
      admin: 20
      owner: 50

# The messages configuration
messages:
  prefix:
    toggle: true
    string: "&8[&9RealmProtector&8] &r"

  general:
    flags:
      enabled: "&a✔ Enabled &r"
      disabled: "&c✘ Disabled &r"

    gui:
      close_button:
        enabled: true # You can disable it, because players can use ESC key to close the inventory
        displayname: "&cClose"
        type: "BARRIER"

    date:
      format: "dd MMM yyy HH:mm:ss" # Example output: 01 Jan 1970 00:00:03
    
    player_chunk_entry:
      claimed:
        title: "&9%land%"
        subtitle: "&fYou have entered a claimed chunk"
      unclaimed:
        title: "&2Wilderness"
        subtitle: "&fRoam the wild!"
  
  gui:
    # GUI for the command: /land info (land name)
    land_info:
      title: "&9Land Information"
      content:
        land_information:
          displayname: "&9Land: &r%land_name%"
          lore:
            - "&aID: &f%land_id%"
            - "&aChunks: &f%chunks%"
            - "&aBalance: &f$%balance%"
            - "&aCreated at: &f%created_at%"
          type: "OAK_SIGN"
        land_owner:
          displayname: "&9Owner: &c%land_owner%"
          type: "PLAYER_HEAD"
        land_members:
          displayname: "&9Members (%members_count%):"
          lore_style: "&a%role_name%&f: &6%member_name%"
          type: "EMERALD"

    # GUI for the command: /land roles flags [role name]
    role_flags:
      title: "&9Role Flags"
      content:
        flag_style:
          displayname: "&7%flag%"
          lore:
            - "&f%description%"
            - "%value%" # The value is "Enabled" or "Disabled" ("messages.general.flags.[enabled/disabled]")
          type: "%flag_item%" # The flag's item type ("messages.gui.role_flags.items")
        role_name:
          displayname: "&9Role: &6%role%"
          type: "PAPER"

    # GUI for the command: /land nature flags
    nature_flags:
      title: "&9Nature Flags"
      content:
        flag_style:
          displayname: "&7%flag%"
          lore:
            - "&f%description%"
            - "%value%" # The value is "Enabled" or "Disabled" ("messages.general.flags.[enabled/disabled]")
          type: "%flag_item%" # The flag's item type ("messages.gui.nature_flags.items")
        land_name:
          displayname: "&9Land: &6%land_name%"
          type: "PAPER"

    flags_description:
      # Role flags
      role_flags:
        breakblocks: "Allow players to break blocks?"
        placeblocks: "Allow players to place blocks?"
        containers: "Allow players to open containers?"
        redstone: "Allow players to configure redstone components?"
        doors: "Allow players to use doors?"
        trapdoors: "Allow players to trapdoors?"
        editsigns: "Allow players to edit signs and hanging signs?"
        emptybuckets: "Allow players to empty any bucket?"
        fillbuckets: "Allow players to fill any bucket?"
        harvestcrops: "Allow players to harvest crops?"
        frostwalker: "Allow players to use Frost Walker boots?"
        shearentities: "Allow players to shear entities?"
        itemframes: "Allow players to spin, break and take off items from item frames?"
        fencegates: "Allow players to use fence gates?"
        buttons: "Allow players to use buttons?"
        levers: "Allow players to use levers?"
        pressureplates: "Allow players to step on pressure plates?"
        bells: "Allow players to use bells?"
        tripwires: "Allow players to step on tripwires and triggers them?"
        armorstands: "Allow players to interact with armor stands?"
        teleporttospawn: "Allow players to visit your land?"
        throwenderpearls: "Allow players to teleport using ender pearls?"
        throwpotions: "Allow players to throw splash potions?"
        damagehostilemobs: "Allow players to hit and kill hostile mobs?"
        damagepassivemobs: "Allow players to hit and kill passive mobs?"
        pvp: "Allow players to PvP each other?"
        usecauldron: "Allow players to interact with cauldrons?"
        pickupitems: "Allow players to drop and pick up items?"
        useanvil: "Allow players to use anvils?"
        createfire: "Allow players to start fire?"
      # Nature flags
      nature_flags:
        hostilemobsspawn: "Allow any hostile mob to spawn?"
        passivemobsspawn: "Allow any passive mob to spawn?"
        leavesdecay: "Allow leaves to decay?"
        firespread: "Allow fire to spread in your land?"
        liquidflow: "Allow any external liquid to enter to your land?"
        tntblockdamage: "Allow TnT damage blocks in your land?"
        respawnanchorblockdamage: "Allow respawn anchors and beds (Nether) damage blocks in your land?"
        pistonsfromwilderness: "Allow blocks to be pushed/pulled by pistons to/from your land?"
        plantgrowth: "Allow any plant to grow in your land?"

  # Command messages
  commands:
    balance:
      land_not_found: "&cYou don't have a land!"
      balance_string: "&aYour land balance: &6$%land_balance%"

    claim:
      chunk_already_claimed: "&cThis chunk has already been claimed."
      missing_land_name: "&cYou must provide your new land name because you will create one with this chunk!"
      land_name_already_taken: "&cThis land name is already been taken, please choose another one."
      chunk_claimed_success: "&aYou have successfully claimed the chunk! &9%chunk_x%, %chunk_z%"

    delete_role:
      land_not_found: "&cYou don't have a land!"
      min_roles_reached: "&cYou cannot delete any role, it should be there at least 2 roles to maintain the land!"
      no_role_provided: "&cYou must provide a role name to delete."
      role_not_found: "&cThis role was not found in your land."
      role_delete_success: "&aSuccessfully deleted the role %role%!"

    deposit:
      land_not_found: "&cYou don't have a land!"
      no_amount_provided: "&cYou must provide the amount to deposit!"
      input_negative_or_zero: "&cThe amount must be higher than 0."
      input_larger_than_player_balance: "&cYou don't have that amount of money."
      input_not_double_or_integer: "&cNot a valid integer or double."
      deposited_success: "&aYou deposited &6$%amount%&a, now your land got &6$%land_balance%&a!"

    info:
      chunk_wilderness: "&cThis is wilderness, you must use this command inside a claimed chunk!"

    new_role:
      land_not_found: "&cYou don't have a land!"
      no_role_provided: "&cYou must provide a new role name to create."
      role_found: "&cThis role does already exist in the land!"
      role_create_success: "&aSuccessfully created a new role!"

    rename_role:
      land_not_found: "&cYou don't have a land!"
      no_role_provided: "&cYou must provide an existing role name to rename."
      role_not_found: "&cThis role does not exist in the land!"
      missing_new_role_name: "&cYou must provide a new role name!"
      role_update_success: "&aSuccessfully renamed &9%old% &ato &&9%new%&a!"

    set_spawn:
      land_not_found: "&cYou don't have a land!"
      chunk_not_claimed: "&cThis chunk is not claimed."
      not_owner_of_chunk: "&cYou don't own this chunk."
      spawn_set_success: "&aSuccessfully updated spawn coordinates: &9%x%, %y%, %z%"

    spawn:
      missing_land_name: "&cYou must provide the land name!"
      land_name_not_found: "&cThis land name doesn't exist."
      missing_permissions_to_teleport: "&cYou do not have permission to teleport to %land_name%."
      spawn_teleport_success: "&aTeleported to &6%land_name%&a: &9%x%, %y%, %z% &a(%world%)"

    trust:
      land_not_found: "&cYou don't have a land!"
      no_playername_provided: "&cYou must name the player to trust."
      playername_not_found: "&cThis playername doens't exist."
      playername_already_trusted: "&cThis playername is already in the land!"
      playername_owner_of_land: "&cYou are the owner of the land."
      no_role_provided: "&cYou must provide a role name for the player."
      role_not_found: "&cThis role was not found in your land."
      player_cannot_have_default_role: "&cThe player cannot have a default (Visitor) role!"
      player_trusted_success: "&aYou trusted &6%player% &ato join the land!"

    unclaim:
      land_not_found: "&cYou don't have a land!"
      chunk_not_claimed: "&cThis chunk is not claimed."
      chunk_not_owned_by_sender: "&cThis chunk is owned by a land that you don't own!"
      confirm_missing: "&7You must confirm to continue..."
      chunk_unclaimed_success: "&aYou have successfully unclaimed this chunk!"
      show_note_land_deleted: "&6Note: Your land has been deleted because you have no chunks to maintain it!"

    untrust:
      land_not_found: "&cYou don't have a land!"
      no_playername_provided: "&cYou must name the player to trust."
      playername_not_found: "&cThis playername doens't exist."
      playername_not_trusted: "&cThis playername is not in the land!"
      player_untrusted_success: "&aYou untrusted &f%player% &ato leave the land."

    update_role_flags:
      land_not_found: "&cYou don't have a land!"
      no_role_provided: "&cYou must provide a role name to update/read it's flags."
      role_not_found: "&cThis role was not found in your land."
      not_valid_flag: "&cThis is not a valid flag."
      missing_boolean_value: "&cYou must provide a boolean value to update the role's flag (true/1 or false/0)."
      not_boolean_value: "&cYou must choose true/1 or false/0, not any kind of other values"
      role_flag_updated_success: "&aThe flag &7%flag% &afor &f%role_name% &ahas been updated to &6%new_value%&a."

    update_nature_flags:
      land_not_found: "&cYou don't have a land!"
      not_valid_flag: "&cThis is not a valid flag."
      missing_boolean_value: "&cYou must provide a boolean value to update the role's flag (true/1 or false/0)."
      not_boolean_value: "&cYou must choose true/1 or false/0, not any kind of other values"
      nature_flag_updated_success: "&aThe flag &7%flag% &ahas been updated to &6%new_value%&a."

    view:
      chunk_wilderness: "&cThis is wilderness, you must use this command inside a claimed chunk!"
      particles_spawned_success: "&aDone! You can check the particles around the land to see the chunks limits."

    withdraw:
      land_not_found: "&cYou don't have a land!"
      no_amount_provided: "&cYou must provide the amount to withdraw!"
      input_negative_or_zero: "&cThe amount must be higher than 0."
      input_larger_than_land_balance: "&cYour land doesn't have that amount of money."
      input_not_double_or_integer: "&cNot a valid integer or double."
      withdrew_success: "&aYou withdrew &6$%amount%&a, now your land got &6$%land_balance%&a!"

  # Error messages when a player doesn't have the permission to do in a land
  permissions:
    # The prefix of the messages
    prefix:
      toggle: true
      string: "&c&lHEY! &r"

    # The suffix of the messages
    suffix:
      toggle: true
      string: " &c(&r%land_name%: &7%flag%&c)"
    
    # The error messages
    messages:
      breakblocks: "&cYou do not have permission to break blocks here"
      placeblocks: "&cYou do not have permission to place blocks here"
      containers: "&cYou do not have permission to open containers here"
      redstone: "&cYou do not have permission to use redstone here"
      doors: "&cYou do not have permission to use doors here"
      trapdoors: "&cYou do not have permission to use trapdoors here"
      editsigns: "&cYou do not have permission to edit signs"
      emptybuckets: "&cYou do not have permission to empty buckets here"
      fillbuckets: "&cYou do not have permission to fill buckets here"
      harvestcrops: "&cYou do not have permission to harvest crops here"
      frostwalker: "&cYou do not have permission to use frost walker boots here"
      shearentities: "&cYou do not have permission to shear sheeps here"
      itemframes: "&cYou do not have permission to interact with item frames here"
      fencegates: "&cYou do not have permission to use fence gates here"
      buttons: "&cYou do not have permission to use buttons here"
      levers: "&cYou do not have permission to use levers here"
      pressureplates: "&cYou do not have permission to use pressure plates here"
      bells: "&cYou do not have permission to use bells here"
      tripwires: "&cYou do not have permission to use tripwires here"
      armorstands: "&cYou do not have permission to take off or put on armors on armor stands here"
      teleporttospawn: "&cYou do not have permission to teleport to spawn"
      throwenderpearls: "&cYou do not have permission to throw ender pearls here"
      throwpotions: "&cYou do not have permission to throw potions here"
      damagehostilemobs: "&cYou do not have permission to hit hostile mobs here"
      damagepassivemobs: "&cYou do not have permission to hit passive mobs here"
      pvp: "&cYou do not have permission to PvP here"
      usecauldron: "&cYou do not have permission to empty or fill cauldrons here"
      pickupitems: "&cYou do not have permission to pickup items here"
      useanvil: "&cYou do not have permission to use anvils here"
      createfire: "&cYou do not have permission to ignite a fire here"

land_roles:
  default:
    # Default roles that must be created when a player creates a new land
    names:
      - "Visitor"
      - "Member"

    permissions:
      # Permissions for the role: Visitor
      Visitor:
        - false # breakblocks
        - false # placeblocks
        - false # containers
        - false # redstone
        - false # doors
        - false # trapdoors
        - false # editsigns
        - false # emptybuckets
        - false # fillbuckets
        - false # harvestcrops
        - false # frostwalker
        - false # shearentities
        - false # itemframes
        - false # fencegates
        - false # buttons
        - false # levers
        - false # pressureplates
        - false # bells
        - false # tripwires
        - false # armorstands
        - false # teleporttospawn
        - false # throwenderpearls
        - false # throwpotions
        - false # damagehostilemobs
        - false # damagepassivemobs
        - false # pvp
        - false # usecauldron
        - true # pickupitems
        - false # useanvil
        - false # createfire

      # Permissions for the role: Member
      Member:
        - true # breakblocks
        - true # placeblocks
        - true # containers
        - true # redstone
        - true # doors
        - true # trapdoors
        - true # editsigns
        - true # emptybuckets
        - true # fillbuckets
        - true # harvestcrops
        - false # frostwalker
        - true # shearentities
        - true # itemframes
        - true # fencegates
        - true # buttons
        - true # levers
        - true # pressureplates
        - true # bells
        - true # tripwires
        - true # armorstands
        - true # teleporttospawn
        - true # throwenderpearls
        - true # throwpotions
        - true # damagehostilemobs
        - false # damagepassivemobs
        - true # pvp
        - true # usecauldron
        - true # pickupitems
        - true # useanvil
        - false # createfire

      # Default permissions if there is a new role created:
      __default__:
        - false # breakblocks
        - false # placeblocks
        - false # containers
        - false # redstone
        - false # doors
        - false # trapdoors
        - false # editsigns
        - false # emptybuckets
        - false # fillbuckets
        - false # harvestcrops
        - false # frostwalker
        - false # shearentities
        - false # itemframes
        - false # fencegates
        - false # buttons
        - false # levers
        - false # pressureplates
        - false # bells
        - false # tripwires
        - false # armorstands
        - false # teleporttospawn
        - false # throwenderpearls
        - false # throwpotions
        - false # damagehostilemobs
        - false # damagepassivemobs
        - false # pvp
        - false # usecauldron
        - true # pickupitems
        - false # useanvil
        - false # createfire