# The main database configuration for the plugin
database:
  provider: "sqlite" # Support databases: sqlite
  path: "/database.db"

# The language file to load
languages:
  locale: "en_US.yml"

ratelimits:
  chunks:
    __DEFAULT__: 10 # If the player's group not found
    default: 10
    vip: 20
    admin: 50
    owner: 100
  roles:
    __DEFAULT__: 10 # If the player's group not found
    default: 5
    vip: 10
    admin: 20
    owner: 50

border_colors: # Note: RBG colors based
  visitor:
      - 255
      - 0
      - 0
  trusted:
    - 255
    - 255
    - 0
  owner:
    - 0
    - 255
    - 0

roles:
  names:
    - "Visitor"
    - "Member"

  __DEFAULT_VISITOR_ROLE__: "Visitor" # Important, and unchangeable role name

  permissions:
      # Permissions for the role: Visitor
    Visitor:
      - false # breakblocks
      - false # placeblocks
      - false # containers
      - false # redstone
      - false # doors
      - false # trapdoors
      - false # editsigns
      - false # emptybuckets
      - false # fillbuckets
      - false # harvestcrops
      - false # frostwalker
      - false # shearentities
      - false # itemframes
      - false # generalinteractions
      - false # fencegates
      - false # buttons
      - false # levers
      - false # pressureplates
      - false # bells
      - false # tripwires
      - false # armorstands
      - false # dyemobs
      - false # renamemobs
      - false # leashmobs
      - false # tradewithvillagers
      - false # teleporttospawn
      - false # throwenderpearls
      - false # throwpotions
      - false # damagehostilemobs
      - false # damagepassivemobs
      - false # pvp
      - false # usecauldron
      - true # pickupitems
      - false # useanvil
      - false # createfire
      - false # usevehicles

    # Permissions for the role: Member
    Member:
      - true # breakblocks
      - true # placeblocks
      - true # containers
      - true # redstone
      - true # doors
      - true # trapdoors
      - true # editsigns
      - true # emptybuckets
      - true # fillbuckets
      - true # harvestcrops
      - false # frostwalker
      - true # shearentities
      - true # itemframes
      - true # generalinteractions
      - true # fencegates
      - true # buttons
      - true # levers
      - true # pressureplates
      - true # bells
      - true # tripwires
      - true # armorstands
      - true # dyemobs
      - true # renamemobs
      - true # leashmobs
      - true # tradewithvillagers
      - true # teleporttospawn
      - true # throwenderpearls
      - true # throwpotions
      - true # damagehostilemobs
      - false # damagepassivemobs
      - true # pvp
      - true # usecauldron
      - true # pickupitems
      - true # useanvil
      - false # createfire
      - true # usevehicles

      # Default permissions if there is a new role created:
    __DEFAULT__:
      - false # breakblocks
      - false # placeblocks
      - false # containers
      - false # redstone
      - false # doors
      - false # trapdoors
      - false # editsigns
      - false # emptybuckets
      - false # fillbuckets
      - false # harvestcrops
      - false # frostwalker
      - false # shearentities
      - false # itemframes
      - false # generalinteractions
      - false # fencegates
      - false # buttons
      - false # levers
      - false # pressureplates
      - false # bells
      - false # tripwires
      - false # armorstands
      - false # dyemobs
      - false # renamemobs
      - false # leashmobs
      - false # tradewithvillagers
      - false # teleporttospawn
      - false # throwenderpearls
      - false # throwpotions
      - false # damagehostilemobs
      - false # damagepassivemobs
      - false # pvp
      - false # usecauldron
      - true # pickupitems
      - false # useanvil
      - false # createfire
      - false # usevehicles