# The main database configuration for the plugin
database:
  provider: "sqlite" # Support databases: sqlite
  path: "/database.db"

# The language file to load (file extension ".yml" is optional)
languages:
  locale: "en_US.yml"

general:
  economy: false # This will enable the economy commands: /land balance, /land deposit, and /land withdraw.

# The ratelimits for each player group
ratelimits:
  # Chunks ratelimit
  chunks:
    __DEFAULT__: 10 # If the player's group not found
    default: 10
    vip: 20
    admin: 50
    owner: 100

  # Land roles ratelimit
  roles:
    __DEFAULT__: 10 # If the player's group not found
    default: 5
    vip: 10
    admin: 20
    owner: 50

# The border particles colors, by default: visitor = (255, 0, 0); trusted = (255, 255); owner = (0, 255, 0)
border_colors: # Note: RBG colors based
  visitor:
      - 255
      - 0
      - 0
  trusted:
    - 255
    - 255
    - 0
  owner:
    - 0
    - 255
    - 0

# Land roles configuration
roles:
  # The role names that should be created once there is a new land created
  # IMPORTANT 1: You must provide 2 role names! More than 2 is OK, but make sure to not exceed follow the ratelimit from "ratelimits.roles.__DEFAULT__".
  # IMPORTANT 2: YOU MUST PROVIDE A ROLE NAME THAT IS EQUAL TO "roles.__DEFAULT_VISITOR_ROLE__" OR ELSE THE ENTIRE PLUGIN WILL BE BUGGED OUT.
  names:
    - "Visitor"
    - "Member"

  # IMPORTANT 1: This role is unchangeable, which means it cannot be deleted or renamed.
  # IMPORTANT 2: YOU MUST PROVIDE THE ROLE NAME THAT EXISTS FROM THE ARRAY "roles.names" OR ELSE THE ENTIRE PLUGIN WILL BE BUGGED OUT.
  __DEFAULT_VISITOR_ROLE__: "Visitor"

  # Configure each role permissions
  permissions:
    # Permissions for the role: Visitor
    Visitor:
      - false # breakblocks
      - false # placeblocks
      - false # containers
      - false # redstone
      - false # doors
      - false # trapdoors
      - false # editsigns
      - false # emptybuckets
      - false # fillbuckets
      - false # harvestcrops
      - false # frostwalker
      - false # shearentities
      - false # itemframes
      - false # generalinteractions
      - false # fencegates
      - false # buttons
      - false # levers
      - false # pressureplates
      - false # bells
      - false # tripwires
      - false # armorstands
      - false # dyemobs
      - false # renamemobs
      - false # leashmobs
      - false # tradewithvillagers
      - false # teleporttospawn
      - false # throwenderpearls
      - false # throwpotions
      - false # damagehostilemobs
      - false # damagepassivemobs
      - false # pvp
      - false # usecauldron
      - true # pickupitems
      - false # useanvil
      - false # createfire
      - false # usevehicles

    # Permissions for the role: Member
    Member:
      - true # breakblocks
      - true # placeblocks
      - true # containers
      - true # redstone
      - true # doors
      - true # trapdoors
      - true # editsigns
      - true # emptybuckets
      - true # fillbuckets
      - true # harvestcrops
      - false # frostwalker
      - true # shearentities
      - true # itemframes
      - true # generalinteractions
      - true # fencegates
      - true # buttons
      - true # levers
      - true # pressureplates
      - true # bells
      - true # tripwires
      - true # armorstands
      - true # dyemobs
      - true # renamemobs
      - true # leashmobs
      - true # tradewithvillagers
      - true # teleporttospawn
      - true # throwenderpearls
      - true # throwpotions
      - true # damagehostilemobs
      - false # damagepassivemobs
      - true # pvp
      - true # usecauldron
      - true # pickupitems
      - true # useanvil
      - false # createfire
      - true # usevehicles

      # Default permissions if there is a new role created:
    __DEFAULT__:
      - false # breakblocks
      - false # placeblocks
      - false # containers
      - false # redstone
      - false # doors
      - false # trapdoors
      - false # editsigns
      - false # emptybuckets
      - false # fillbuckets
      - false # harvestcrops
      - false # frostwalker
      - false # shearentities
      - false # itemframes
      - false # generalinteractions
      - false # fencegates
      - false # buttons
      - false # levers
      - false # pressureplates
      - false # bells
      - false # tripwires
      - false # armorstands
      - false # dyemobs
      - false # renamemobs
      - false # leashmobs
      - false # tradewithvillagers
      - false # teleporttospawn
      - false # throwenderpearls
      - false # throwpotions
      - false # damagehostilemobs
      - false # damagepassivemobs
      - false # pvp
      - false # usecauldron
      - true # pickupitems
      - false # useanvil
      - false # createfire
      - false # usevehicles