name: RealmProtection
main: realmprotection.RealmProtection
version: 1.0.0
api-version: 1.20
commands:
  lands:
    description: 'The main RealmProtection command'
    usage: '/<command> [subcommand]'
    aliases:
     - land