name: XTremeLands
main: xtremelands.Plugin
version: 0.1.0
api-version: 1.20
commands:
  ping:
    description: 'Replies with pong!'
    usage: '/<command>'
  gui:
    description: 'Shows an example of gui'
    usage: '/<command>'
  lands:
    description: 'Plot command'
    usage: '/<command> [claim/unclaim/info]'
    aliases:
     - land